#!/usr/bin/env python3

table = "../../submodules/linux/arch/x86/entry/syscalls/syscall_64.tbl"

print("// DO NOT MODIFY -- GENERATED BY " + __file__.split("/")[-1])
print()

with open(table, "r") as f:
    for line in f:
        if len(line) == 0:
            continue
        if not line[0].isdigit():
            continue

        pieces = line.split()
        nr = int(pieces[0])
        abi = pieces[1]
        name = pieces[2]

        if abi == "x32":
            continue
        
        # ignoring entries with missing <entry point>
        if len(pieces) <= 3:
            continue

        entry_point = pieces[3]
        # it exists, but only technically, always returns ENOSYS, feels useless
        if entry_point == "sys_ni_syscall":
            continue
        
        print(f"X({nr}, {name})")

print()
print("#undef X")

# IVL generate_header("syscall_numbers_X")
