// generated, dont ask how

IVLSYS1(inotify_init1, int, flags)
IVLSYS0(inotify_init)
IVLSYS3(inotify_add_watch, int, fd, const char *, pathname, uint32_t, mask)
IVLSYS2(inotify_rm_watch, int, fd, int32_t, wd)
IVLSYS2(fanotify_init, unsigned int, flags, unsigned int, event_f_flags)
IVLSYS5(fanotify_mark, int, fanotify_fd, unsigned int, flags, uint64_t, mask, int, dfd, const char *, pathname)
IVLSYS2(msgget, key_t, key, int, msgflg)
IVLSYS3(msgctl, int, msqid, int, cmd, struct msqid_ds *, buf)
IVLSYS4(msgsnd, int, msqid, struct msgbuf *, msgp, size_t, msgsz, int, msgflg)
IVLSYS5(msgrcv, int, msqid, struct msgbuf *, msgp, size_t, msgsz, long, msgtyp, int, msgflg)
IVLSYS4(cachestat, unsigned int, fd, struct cachestat_range *, cstat_range, struct cachestat *, cstat, unsigned int, flags)
IVLSYS3(semget, key_t, key, int, nsems, int, semflg)
IVLSYS4(semctl, int, semid, int, semnum, int, cmd, unsigned long, arg)
IVLSYS4(semtimedop, int, semid, struct sembuf *, tsops, unsigned int, nsops, const struct __kernel_timespec *, timeout)
IVLSYS3(semop, int, semid, struct sembuf *, tsops, unsigned, nsops)
IVLSYS3(shmget, key_t, key, size_t, size, int, shmflg)
IVLSYS3(shmctl, int, shmid, int, cmd, struct shmid_ds *, buf)
IVLSYS3(shmat, int, shmid, char *, shmaddr, int, shmflg)
IVLSYS1(shmdt, char *, shmaddr)
IVLSYS4(mq_open, const char *, u_name, int, oflag, umode_t, mode, struct mq_attr *, u_attr)
IVLSYS1(mq_unlink, const char *, u_name)
IVLSYS5(mq_timedsend, mqd_t, mqdes, const char *, u_msg_ptr, size_t, msg_len, unsigned int, msg_prio, const struct __kernel_timespec *, u_abs_timeout)
IVLSYS5(mq_timedreceive, mqd_t, mqdes, char *, u_msg_ptr, size_t, msg_len, unsigned int *, u_msg_prio, const struct __kernel_timespec *, u_abs_timeout)
IVLSYS2(mq_notify, mqd_t, mqdes, const struct sigevent *, u_notification)
IVLSYS3(mq_getsetattr, mqd_t, mqdes, const struct mq_attr *, u_mqstat, struct mq_attr *, u_omqstat)
IVLSYS2(process_mrelease, int, pidfd, unsigned int, flags)
IVLSYS5(add_key, const char *, _type, const char *, _description, const void *, _payload, size_t, plen, key_serial_t, ringid)
IVLSYS4(request_key, const char *, _type, const char *, _description, const char *, _callout_info, key_serial_t, destringid)
IVLSYS5(keyctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
IVLSYS4(fadvise64, int, fd, loff_t, offset, size_t, len, int, advice)
IVLSYS3(readahead, int, fd, loff_t, offset, size_t, count)
IVLSYS3(sched_setscheduler, pid_t, pid, int, policy, struct sched_param *, param)
IVLSYS2(sched_setparam, pid_t, pid, struct sched_param *, param)
IVLSYS3(sched_setattr, pid_t, pid, struct sched_attr *, uattr, unsigned int, flags)
IVLSYS1(sched_getscheduler, pid_t, pid)
IVLSYS2(sched_getparam, pid_t, pid, struct sched_param *, param)
IVLSYS4(sched_getattr, pid_t, pid, struct sched_attr *, uattr, unsigned int, usize, unsigned int, flags)
IVLSYS3(sched_setaffinity, pid_t, pid, unsigned int, len, unsigned long *, user_mask_ptr)
IVLSYS3(sched_getaffinity, pid_t, pid, unsigned int, len, unsigned long *, user_mask_ptr)
IVLSYS0(sched_yield)
IVLSYS1(sched_get_priority_max, int, policy)
IVLSYS1(sched_get_priority_min, int, policy)
IVLSYS2(sched_rr_get_interval, pid_t, pid, struct __kernel_timespec *, interval)
IVLSYS3(membarrier, int, cmd, unsigned int, flags, int, cpu_id)
IVLSYS3(syslog, int, type, char *, buf, int, len)
IVLSYS4(quotactl, unsigned int, cmd, const char *, special, qid_t, id, void *, addr)
IVLSYS4(quotactl_fd, unsigned int, fd, unsigned int, cmd, qid_t, id, void *, addr)
IVLSYS6(io_uring_enter, unsigned int, fd, uint32_t, to_submit, uint32_t, min_complete, uint32_t, flags, const void *, argp, size_t, argsz)
IVLSYS2(io_uring_setup, uint32_t, entries, struct io_uring_params *, params)
IVLSYS3(landlock_create_ruleset, const struct landlock_ruleset_attr *const, attr, const size_t, size, const uint32_t, flags)
IVLSYS4(landlock_add_rule, const int, ruleset_fd, const enum landlock_rule_type, rule_type, const void *const, rule_attr, const uint32_t, flags)
IVLSYS2(landlock_restrict_self, const int, ruleset_fd, const uint32_t, flags)
IVLSYS2(delete_module, const char *, name_user, unsigned int, flags)
IVLSYS3(init_module, void *, umod, unsigned long, len, const char *, uargs)
IVLSYS3(finit_module, int, fd, const char *, uargs, int, flags)
IVLSYS3(ioprio_set, int, which, int, who, int, ioprio)
IVLSYS2(ioprio_get, int, which, int, who)
IVLSYS2(mlock, unsigned long, start, size_t, len)
IVLSYS3(mlock2, unsigned long, start, size_t, len, int, flags)
IVLSYS2(munlock, unsigned long, start, size_t, len)
IVLSYS1(mlockall, int, flags)
IVLSYS0(munlockall)
IVLSYS1(brk, unsigned long, brk)
IVLSYS2(munmap, unsigned long, addr, size_t, len)
IVLSYS5(remap_file_pages, unsigned long, start, unsigned long, size, unsigned long, prot, unsigned long, pgoff, unsigned long, flags)
IVLSYS1(time, __kernel_old_time_t *, tloc)
IVLSYS2(gettimeofday, struct __kernel_old_timeval *, tv, struct timezone *, tz)
IVLSYS2(settimeofday, struct __kernel_old_timeval *, tv, struct timezone *, tz)
IVLSYS1(adjtimex, struct __kernel_timex *, txc_p)
IVLSYS3(mincore, unsigned long, start, size_t, len, unsigned char *, vec)
IVLSYS4(io_uring_register, unsigned int, fd, unsigned int, opcode, void *, arg, unsigned int, nr_args)
IVLSYS2(nanosleep, struct __kernel_timespec *, rqtp, struct __kernel_timespec *, rmtp)
IVLSYS5(mremap, unsigned long, addr, unsigned long, old_len, unsigned long, new_len, unsigned long, flags, unsigned long, new_addr)
IVLSYS3(mprotect, unsigned long, start, size_t, len, unsigned long, prot)
IVLSYS4(pkey_mprotect, unsigned long, start, size_t, len, unsigned long, prot, int, pkey)
IVLSYS2(pkey_alloc, unsigned long, flags, unsigned long, init_val)
IVLSYS1(pkey_free, int, pkey)
IVLSYS3(msync, unsigned long, start, size_t, len, int, flags)
IVLSYS3(timer_create, const clockid_t, which_clock, struct sigevent *, timer_event_spec, timer_t *, created_timer_id)
IVLSYS2(timer_gettime, timer_t, timer_id, struct __kernel_itimerspec *, setting)
IVLSYS1(timer_getoverrun, timer_t, timer_id)
IVLSYS4(timer_settime, timer_t, timer_id, int, flags, const struct __kernel_itimerspec *, new_setting, struct __kernel_itimerspec *, old_setting)
IVLSYS1(timer_delete, timer_t, timer_id)
IVLSYS2(clock_settime, const clockid_t, which_clock, const struct __kernel_timespec *, tp)
IVLSYS2(clock_gettime, const clockid_t, which_clock, struct __kernel_timespec *, tp)
IVLSYS2(clock_adjtime, const clockid_t, which_clock, struct __kernel_timex *, utx)
IVLSYS2(clock_getres, const clockid_t, which_clock, struct __kernel_timespec *, tp)
IVLSYS4(clock_nanosleep, const clockid_t, which_clock, int, flags, const struct __kernel_timespec *, rqtp, struct __kernel_timespec *, rmtp)
IVLSYS2(getitimer, int, which, struct __kernel_old_itimerval *, value)
IVLSYS1(alarm, unsigned int, seconds)
IVLSYS3(setitimer, int, which, struct __kernel_old_itimerval *, value, struct __kernel_old_itimerval *, ovalue)
IVLSYS2(set_robust_list, struct robust_list_head *, head, size_t, len)
IVLSYS3(get_robust_list, int, pid, struct robust_list_head * *, head_ptr, size_t *, len_ptr)
IVLSYS6(futex, uint32_t *, uaddr, int, op, uint32_t, val, const struct __kernel_timespec *, utime, uint32_t *, uaddr2, uint32_t, val3)
IVLSYS5(futex_waitv, struct futex_waitv *, waiters, unsigned int, nr_futexes, unsigned int, flags, struct __kernel_timespec *, timeout, clockid_t, clockid)
IVLSYS4(futex_wake, void *, uaddr, unsigned long, mask, int, nr, unsigned int, flags)
IVLSYS6(futex_wait, void *, uaddr, unsigned long, val, unsigned long, mask, unsigned int, flags, struct __kernel_timespec *, timeout, clockid_t, clockid)
IVLSYS4(futex_requeue, struct futex_waitv *, waiters, unsigned int, flags, int, nr_wake, int, nr_requeue)
IVLSYS4(lsm_set_self_attr, unsigned int, attr, struct lsm_ctx *, ctx, uint32_t, size, uint32_t, flags)
IVLSYS4(lsm_get_self_attr, unsigned int, attr, struct lsm_ctx *, ctx, uint32_t *, size, uint32_t, flags)
IVLSYS3(lsm_list_modules, uint64_t *, ids, uint32_t *, size, uint32_t, flags)
IVLSYS6(process_vm_readv, pid_t, pid, const struct iovec *, lvec, unsigned long, liovcnt, const struct iovec *, rvec, unsigned long, riovcnt, unsigned long, flags)
IVLSYS6(process_vm_writev, pid_t, pid, const struct iovec *, lvec, unsigned long, liovcnt, const struct iovec *, rvec, unsigned long, riovcnt, unsigned long, flags)
IVLSYS3(mseal, unsigned long, start, size_t, len, unsigned long, flags)
IVLSYS3(madvise, unsigned long, start, size_t, len_in, int, behavior)
IVLSYS5(process_madvise, int, pidfd, const struct iovec *, vec, size_t, vlen, int, behavior, unsigned int, flags)
IVLSYS1(swapoff, const char *, specialfile)
IVLSYS2(swapon, const char *, specialfile, int, swap_flags)
IVLSYS4(set_mempolicy_home_node, unsigned long, start, unsigned long, len, unsigned long, home_node, unsigned long, flags)
IVLSYS6(mbind, unsigned long, start, unsigned long, len, unsigned long, mode, const unsigned long *, nmask, unsigned long, maxnode, unsigned int, flags)
IVLSYS3(set_mempolicy, int, mode, const unsigned long *, nmask, unsigned long, maxnode)
IVLSYS4(migrate_pages, pid_t, pid, unsigned long, maxnode, const unsigned long *, old_nodes, const unsigned long *, new_nodes)
IVLSYS5(get_mempolicy, int *, policy, unsigned long *, nmask, unsigned long, maxnode, unsigned long, addr, unsigned long, flags)
IVLSYS2(arch_prctl, int, option, unsigned long, arg2)
IVLSYS0(rt_sigreturn)
IVLSYS3(bpf, int, cmd, union bpf_attr *, uattr, unsigned int, size)
IVLSYS5(perf_event_open, struct perf_event_attr *, attr_uptr, pid_t, pid, int, cpu, int, group_fd, unsigned long, flags)
IVLSYS3(ioperm, unsigned long, from, unsigned long, num, int, turn_on)
IVLSYS1(iopl, unsigned int, level)
IVLSYS6(move_pages, pid_t, pid, unsigned long, nr_pages, const void * *, pages, const int *, nodes, int *, status, int, flags)
IVLSYS3(modify_ldt, int , func , void * , ptr , unsigned long , bytecount)
IVLSYS6(mmap, unsigned long, addr, unsigned long, len, unsigned long, prot, unsigned long, flags, unsigned long, fd, unsigned long, off)
IVLSYS1(set_tid_address, int *, tidptr)
IVLSYS0(fork)
IVLSYS0(vfork)
IVLSYS5(clone, unsigned long, clone_flags, unsigned long, newsp, int *, parent_tidptr, int *, child_tidptr, unsigned long, tls)
IVLSYS2(clone3, struct clone_args *, uargs, size_t, size)
IVLSYS1(unshare, unsigned long, unshare_flags)
IVLSYS1(personality, unsigned int, personality)
IVLSYS2(truncate, const char *, path, long, length)
IVLSYS2(ftruncate, unsigned int, fd, off_t, length)
IVLSYS4(fallocate, int, fd, int, mode, loff_t, offset, loff_t, len)
IVLSYS3(faccessat, int, dfd, const char *, filename, int, mode)
IVLSYS4(faccessat2, int, dfd, const char *, filename, int, mode, int, flags)
IVLSYS2(access, const char *, filename, int, mode)
IVLSYS1(chdir, const char *, filename)
IVLSYS1(fchdir, unsigned int, fd)
IVLSYS1(chroot, const char *, filename)
IVLSYS2(fchmod, unsigned int, fd, umode_t, mode)
IVLSYS4(fchmodat2, int, dfd, const char *, filename, umode_t, mode, unsigned int, flags)
IVLSYS3(fchmodat, int, dfd, const char *, filename, umode_t, mode)
IVLSYS2(chmod, const char *, filename, umode_t, mode)
IVLSYS5(fchownat, int, dfd, const char *, filename, uid_t, user, gid_t, group, int, flag)
IVLSYS3(chown, const char *, filename, uid_t, user, gid_t, group)
IVLSYS3(lchown, const char *, filename, uid_t, user, gid_t, group)
IVLSYS3(fchown, unsigned int, fd, uid_t, user, gid_t, group)
IVLSYS3(open, const char *, filename, int, flags, umode_t, mode)
IVLSYS4(openat, int, dfd, const char *, filename, int, flags, umode_t, mode)
IVLSYS4(openat2, int, dfd, const char *, filename, struct open_how *, how, size_t, usize)
IVLSYS2(creat, const char *, pathname, umode_t, mode)
IVLSYS1(close, unsigned int, fd)
IVLSYS0(vhangup)
IVLSYS1(memfd_secret, unsigned int, flags)
IVLSYS3(lseek, unsigned int, fd, off_t, offset, unsigned int, whence)
IVLSYS3(read, unsigned int, fd, char *, buf, size_t, count)
IVLSYS3(write, unsigned int, fd, const char *, buf, size_t, count)
IVLSYS4(pread64, unsigned int, fd, char *, buf, size_t, count, loff_t, pos)
IVLSYS4(pwrite64, unsigned int, fd, const char *, buf, size_t, count, loff_t, pos)
IVLSYS3(readv, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen)
IVLSYS3(writev, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen)
IVLSYS5(preadv, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
IVLSYS6(preadv2, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
IVLSYS5(pwritev, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h)
IVLSYS6(pwritev2, unsigned long, fd, const struct iovec *, vec, unsigned long, vlen, unsigned long, pos_l, unsigned long, pos_h, rwf_t, flags)
IVLSYS4(sendfile, int, out_fd, int, in_fd, off_t *, offset, size_t, count)
IVLSYS6(copy_file_range, int, fd_in, loff_t *, off_in, int, fd_out, loff_t *, off_out, size_t, len, unsigned int, flags)
IVLSYS2(memfd_create, const char *, uname, unsigned int, flags)
IVLSYS2(stat, const char *, filename, struct __old_kernel_stat *, statbuf)
IVLSYS2(lstat, const char *, filename, struct __old_kernel_stat *, statbuf)
IVLSYS2(fstat, unsigned int, fd, struct __old_kernel_stat *, statbuf)
IVLSYS4(newfstatat, int, dfd, const char *, filename, struct stat *, statbuf, int, flag)
IVLSYS4(readlinkat, int, dfd, const char *, pathname, char *, buf, int, bufsiz)
IVLSYS3(readlink, const char *, path, char *, buf, int, bufsiz)
IVLSYS5(statx, int, dfd, const char *, filename, unsigned, flags, unsigned int, mask, struct statx *, buffer)
IVLSYS3(execve, const char *, filename, const char *const *, argv, const char *const *, envp)
IVLSYS5(execveat, int, fd, const char *, filename, const char *const *, argv, const char *const *, envp, int, flags)
IVLSYS2(pipe2, int *, fildes, int, flags)
IVLSYS1(pipe, int *, fildes)
IVLSYS4(mknodat, int, dfd, const char *, filename, umode_t, mode, unsigned int, dev)
IVLSYS3(mknod, const char *, filename, umode_t, mode, unsigned, dev)
IVLSYS3(mkdirat, int, dfd, const char *, pathname, umode_t, mode)
IVLSYS2(mkdir, const char *, pathname, umode_t, mode)
IVLSYS1(rmdir, const char *, pathname)
IVLSYS3(unlinkat, int, dfd, const char *, pathname, int, flag)
IVLSYS1(unlink, const char *, pathname)
IVLSYS3(symlinkat, const char *, oldname, int, newdfd, const char *, newname)
IVLSYS2(symlink, const char *, oldname, const char *, newname)
IVLSYS5(linkat, int, olddfd, const char *, oldname, int, newdfd, const char *, newname, int, flags)
IVLSYS2(link, const char *, oldname, const char *, newname)
IVLSYS5(renameat2, int, olddfd, const char *, oldname, int, newdfd, const char *, newname, unsigned int, flags)
IVLSYS4(renameat, int, olddfd, const char *, oldname, int, newdfd, const char *, newname)
IVLSYS2(rename, const char *, oldname, const char *, newname)
IVLSYS3(fcntl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
IVLSYS3(ioctl, unsigned int, fd, unsigned int, cmd, unsigned long, arg)
IVLSYS3(getdents, unsigned int, fd, struct linux_dirent *, dirent, unsigned int, count)
IVLSYS3(getdents64, unsigned int, fd, struct linux_dirent64 *, dirent, unsigned int, count)
IVLSYS1(exit, int, error_code)
IVLSYS1(exit_group, int, error_code)
IVLSYS5(waitid, int, which, pid_t, upid, struct siginfo *, infop, int, options, struct rusage *, ru)
IVLSYS4(wait4, pid_t, upid, int *, stat_addr, int, options, struct rusage *, ru)
IVLSYS0(uretprobe)
IVLSYS5(select, int, n, fd_set *, inp, fd_set *, outp, fd_set *, exp, struct __kernel_old_timeval *, tvp)
IVLSYS6(pselect6, int, n, fd_set *, inp, fd_set *, outp, fd_set *, exp, struct __kernel_timespec *, tsp, void *, sig)
IVLSYS3(poll, struct pollfd *, ufds, unsigned int, nfds, int, timeout_msecs)
IVLSYS5(ppoll, struct pollfd *, ufds, unsigned int, nfds, struct __kernel_timespec *, tsp, const sigset_t *, sigmask, size_t, sigsetsize)
IVLSYS3(map_shadow_stack, unsigned long, addr, unsigned long, size, unsigned int, flags)
IVLSYS3(close_range, unsigned int, fd, unsigned int, max_fd, unsigned int, flags)
IVLSYS3(dup3, unsigned int, oldfd, unsigned int, newfd, int, flags)
IVLSYS2(dup2, unsigned int, oldfd, unsigned int, newfd)
IVLSYS1(dup, unsigned int, fildes)
IVLSYS3(sysfs, int, option, unsigned long, arg1, unsigned long, arg2)
IVLSYS2(umount2, char *, name, int, flags)
IVLSYS3(open_tree, int, dfd, const char *, filename, unsigned, flags)
IVLSYS5(mount, char *, dev_name, char *, dir_name, char *, type, unsigned long, flags, void *, data)
IVLSYS3(fsmount, int, fs_fd, unsigned int, flags, unsigned int, attr_flags)
IVLSYS5(move_mount, int, from_dfd, const char *, from_pathname, int, to_dfd, const char *, to_pathname, unsigned int, flags)
IVLSYS2(pivot_root, const char *, new_root, const char *, put_old)
IVLSYS5(mount_setattr, int, dfd, const char *, path, unsigned int, flags, struct mount_attr *, uattr, size_t, usize)
IVLSYS4(statmount, const struct mnt_id_req *, req, struct statmount *, buf, size_t, bufsize, unsigned int, flags)
IVLSYS4(listmount, const struct mnt_id_req *, req, uint64_t *, mnt_ids, size_t, nr_mnt_ids, unsigned int, flags)
IVLSYS6(setxattrat, int, dfd, const char *, pathname, unsigned int, at_flags, const char *, name, const struct xattr_args *, uargs, size_t, usize)
IVLSYS5(setxattr, const char *, pathname, const char *, name, const void *, value, size_t, size, int, flags)
IVLSYS5(lsetxattr, const char *, pathname, const char *, name, const void *, value, size_t, size, int, flags)
IVLSYS5(fsetxattr, int, fd, const char *, name, const void *,value, size_t, size, int, flags)
IVLSYS6(getxattrat, int, dfd, const char *, pathname, unsigned int, at_flags, const char *, name, struct xattr_args *, uargs, size_t, usize)
IVLSYS4(getxattr, const char *, pathname, const char *, name, void *, value, size_t, size)
IVLSYS4(lgetxattr, const char *, pathname, const char *, name, void *, value, size_t, size)
IVLSYS4(fgetxattr, int, fd, const char *, name, void *, value, size_t, size)
IVLSYS5(listxattrat, int, dfd, const char *, pathname, unsigned int, at_flags, char *, list, size_t, size)
IVLSYS3(listxattr, const char *, pathname, char *, list, size_t, size)
IVLSYS3(llistxattr, const char *, pathname, char *, list, size_t, size)
IVLSYS3(flistxattr, int, fd, char *, list, size_t, size)
IVLSYS4(removexattrat, int, dfd, const char *, pathname, unsigned int, at_flags, const char *, name)
IVLSYS2(removexattr, const char *, pathname, const char *, name)
IVLSYS2(lremovexattr, const char *, pathname, const char *, name)
IVLSYS2(fremovexattr, int, fd, const char *, name)
IVLSYS2(capget, cap_user_header_t, header, cap_user_data_t, dataptr)
IVLSYS2(capset, cap_user_header_t, header, const cap_user_data_t, data)
IVLSYS4(ptrace, long, request, long, pid, unsigned long, addr, unsigned long, data)
IVLSYS4(vmsplice, int, fd, const struct iovec *, uiov, unsigned long, nr_segs, unsigned int, flags)
IVLSYS6(splice, int, fd_in, loff_t *, off_in, int, fd_out, loff_t *, off_out, size_t, len, unsigned int, flags)
IVLSYS4(tee, int, fdin, int, fdout, size_t, len, unsigned int, flags)
IVLSYS0(restart_syscall)
IVLSYS4(rt_sigprocmask, int, how, sigset_t *, nset, sigset_t *, oset, size_t, sigsetsize)
IVLSYS2(rt_sigpending, sigset_t *, uset, size_t, sigsetsize)
IVLSYS4(rt_sigtimedwait, const sigset_t *, uthese, siginfo_t *, uinfo, const struct __kernel_timespec *, uts, size_t, sigsetsize)
IVLSYS2(kill, pid_t, pid, int, sig)
IVLSYS4(pidfd_send_signal, int, pidfd, int, sig, siginfo_t *, info, unsigned int, flags)
IVLSYS3(tgkill, pid_t, tgid, pid_t, pid, int, sig)
IVLSYS2(tkill, pid_t, pid, int, sig)
IVLSYS3(rt_sigqueueinfo, pid_t, pid, int, sig, siginfo_t *, uinfo)
IVLSYS4(rt_tgsigqueueinfo, pid_t, tgid, pid_t, pid, int, sig, siginfo_t *, uinfo)
IVLSYS2(sigaltstack,const stack_t *,uss, stack_t *,uoss)
IVLSYS4(rt_sigaction, int, sig, const struct sigaction *, act, struct sigaction *, oact, size_t, sigsetsize)
IVLSYS0(pause)
IVLSYS2(rt_sigsuspend, sigset_t *, unewset, size_t, sigsetsize)
IVLSYS3(setpriority, int, which, int, who, int, niceval)
IVLSYS2(getpriority, int, which, int, who)
IVLSYS2(setregid, gid_t, rgid, gid_t, egid)
IVLSYS1(setgid, gid_t, gid)
IVLSYS2(setreuid, uid_t, ruid, uid_t, euid)
IVLSYS1(setuid, uid_t, uid)
IVLSYS3(setresuid, uid_t, ruid, uid_t, euid, uid_t, suid)
IVLSYS3(getresuid, uid_t *, ruidp, uid_t *, euidp, uid_t *, suidp)
IVLSYS3(setresgid, gid_t, rgid, gid_t, egid, gid_t, sgid)
IVLSYS3(getresgid, gid_t *, rgidp, gid_t *, egidp, gid_t *, sgidp)
IVLSYS1(setfsuid, uid_t, uid)
IVLSYS1(setfsgid, gid_t, gid)
IVLSYS0(getpid)
IVLSYS0(gettid)
IVLSYS0(getppid)
IVLSYS0(getuid)
IVLSYS0(geteuid)
IVLSYS0(getgid)
IVLSYS0(getegid)
IVLSYS1(times, struct tms *, tbuf)
IVLSYS2(setpgid, pid_t, pid, pid_t, pgid)
IVLSYS1(getpgid, pid_t, pid)
IVLSYS0(getpgrp)
IVLSYS1(getsid, pid_t, pid)
IVLSYS0(setsid)
IVLSYS1(uname, struct old_utsname *, name)
IVLSYS2(sethostname, char *, name, int, len)
IVLSYS2(setdomainname, char *, name, int, len)
IVLSYS2(getrlimit, unsigned int, resource, struct rlimit *, rlim)
IVLSYS4(prlimit64, pid_t, pid, unsigned int, resource, const struct rlimit64 *, new_rlim, struct rlimit64 *, old_rlim)
IVLSYS2(setrlimit, unsigned int, resource, struct rlimit *, rlim)
IVLSYS2(getrusage, int, who, struct rusage *, ru)
IVLSYS1(umask, int, mask)
IVLSYS5(prctl, int, option, unsigned long, arg2, unsigned long, arg3, unsigned long, arg4, unsigned long, arg5)
IVLSYS3(getcpu, unsigned *, cpup, unsigned *, nodep, struct getcpu_cache *, unused)
IVLSYS1(sysinfo, struct sysinfo *, info)
IVLSYS0(sync)
IVLSYS1(syncfs, int, fd)
IVLSYS1(fsync, unsigned int, fd)
IVLSYS1(fdatasync, unsigned int, fd)
IVLSYS4(sync_file_range, int, fd, loff_t, offset, loff_t, nbytes, unsigned int, flags)
IVLSYS4(utimensat, int, dfd, const char *, filename, struct __kernel_timespec *, utimes, int, flags)
IVLSYS3(futimesat, int, dfd, const char *, filename, struct __kernel_old_timeval *, utimes)
IVLSYS2(utimes, char *, filename, struct __kernel_old_timeval *, utimes)
IVLSYS2(utime, char *, filename, struct utimbuf *, times)
IVLSYS2(getcwd, char *, buf, unsigned long, size)
IVLSYS2(pidfd_open, pid_t, pid, unsigned int, flags)
IVLSYS3(pidfd_getfd, int, pidfd, int, fd, unsigned int, flags)
IVLSYS2(statfs, const char *, pathname, struct statfs *, buf)
IVLSYS2(fstatfs, unsigned int, fd, struct statfs *, buf)
IVLSYS2(ustat, unsigned, dev, struct ustat *, ubuf)
IVLSYS2(setns, int, fd, int, flags)
IVLSYS2(fsopen, const char *, _fs_name, unsigned int, flags)
IVLSYS3(fspick, int, dfd, const char *, path, unsigned int, flags)
IVLSYS5(fsconfig, int, fd, unsigned int, cmd, const char *, _key, const void *, _value, int, aux)
IVLSYS4(reboot, int, magic1, int, magic2, unsigned int, cmd, void *, arg)
IVLSYS2(getgroups, int, gidsetsize, gid_t *, grouplist)
IVLSYS2(setgroups, int, gidsetsize, gid_t *, grouplist)
IVLSYS5(kcmp, pid_t, pid1, pid_t, pid2, int, type, unsigned long, idx1, unsigned long, idx2)
IVLSYS1(epoll_create1, int, flags)
IVLSYS1(epoll_create, int, size)
IVLSYS4(epoll_ctl, int, epfd, int, op, int, fd, struct epoll_event *, event)
IVLSYS4(epoll_wait, int, epfd, struct epoll_event *, events, int, maxevents, int, timeout)
IVLSYS6(epoll_pwait, int, epfd, struct epoll_event *, events, int, maxevents, int, timeout, const sigset_t *, sigmask, size_t, sigsetsize)
IVLSYS6(epoll_pwait2, int, epfd, struct epoll_event *, events, int, maxevents, const struct __kernel_timespec *, timeout, const sigset_t *, sigmask, size_t, sigsetsize)
IVLSYS4(signalfd4, int, ufd, sigset_t *, user_mask, size_t, sizemask, int, flags)
IVLSYS3(signalfd, int, ufd, sigset_t *, user_mask, size_t, sizemask)
IVLSYS1(acct, const char *, name)
IVLSYS2(timerfd_create, int, clockid, int, flags)
IVLSYS4(timerfd_settime, int, ufd, int, flags, const struct __kernel_itimerspec *, utmr, struct __kernel_itimerspec *, otmr)
IVLSYS2(timerfd_gettime, int, ufd, struct __kernel_itimerspec *, otmr)
IVLSYS2(eventfd2, unsigned int, count, int, flags)
IVLSYS1(eventfd, unsigned int, count)
IVLSYS4(kexec_load, unsigned long, entry, unsigned long, nr_segments, struct kexec_segment *, segments, unsigned long, flags)
IVLSYS1(userfaultfd, int, flags)
IVLSYS2(io_setup, unsigned, nr_events, aio_context_t *, ctxp)
IVLSYS1(io_destroy, aio_context_t, ctx)
IVLSYS3(io_submit, aio_context_t, ctx_id, long, nr, struct iocb * *, iocbpp)
IVLSYS3(io_cancel, aio_context_t, ctx_id, struct iocb *, iocb, struct io_event *, result)
IVLSYS5(io_getevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event *, events, struct __kernel_timespec *, timeout)
IVLSYS6(io_pgetevents, aio_context_t, ctx_id, long, min_nr, long, nr, struct io_event *, events, struct __kernel_timespec *, timeout, const struct __aio_sigset *, usig)
IVLSYS5(kexec_file_load, int, kernel_fd, int, initrd_fd, unsigned long, cmdline_len, const char *, cmdline_ptr, unsigned long, flags)
IVLSYS2(flock, unsigned int, fd, unsigned int, cmd)
IVLSYS5(name_to_handle_at, int, dfd, const char *, name, struct file_handle *, handle, void *, mnt_id, int, flag)
IVLSYS3(open_by_handle_at, int, mountdirfd, struct file_handle *, handle, int, flags)
IVLSYS3(seccomp, unsigned int, op, unsigned int, flags, void *, uargs)
IVLSYS4(rseq, struct rseq *, rseq, uint32_t, rseq_len, int, flags, uint32_t, sig)
IVLSYS3(getrandom, char *, ubuf, size_t, len, unsigned int, flags)
IVLSYS3(socket, int, family, int, type, int, protocol)
IVLSYS4(socketpair, int, family, int, type, int, protocol, int *, usockvec)
IVLSYS3(bind, int, fd, struct sockaddr *, umyaddr, int, addrlen)
IVLSYS2(listen, int, fd, int, backlog)
IVLSYS4(accept4, int, fd, struct sockaddr *, upeer_sockaddr, int *, upeer_addrlen, int, flags)
IVLSYS3(accept, int, fd, struct sockaddr *, upeer_sockaddr, int *, upeer_addrlen)
IVLSYS3(connect, int, fd, struct sockaddr *, uservaddr, int, addrlen)
IVLSYS3(getsockname, int, fd, struct sockaddr *, usockaddr, int *, usockaddr_len)
IVLSYS3(getpeername, int, fd, struct sockaddr *, usockaddr, int *, usockaddr_len)
IVLSYS6(sendto, int, fd, void *, buff, size_t, len, unsigned int, flags, struct sockaddr *, addr, int, addr_len)
IVLSYS6(recvfrom, int, fd, void *, ubuf, size_t, size, unsigned int, flags, struct sockaddr *, addr, int *, addr_len)
IVLSYS5(setsockopt, int, fd, int, level, int, optname, char *, optval, int, optlen)
IVLSYS5(getsockopt, int, fd, int, level, int, optname, char *, optval, int *, optlen)
IVLSYS2(shutdown, int, fd, int, how)
IVLSYS3(sendmsg, int, fd, struct user_msghdr *, msg, unsigned int, flags)
IVLSYS4(sendmmsg, int, fd, struct mmsghdr *, mmsg, unsigned int, vlen, unsigned int, flags)
IVLSYS3(recvmsg, int, fd, struct user_msghdr *, msg, unsigned int, flags)
IVLSYS5(recvmmsg, int, fd, struct mmsghdr *, mmsg, unsigned int, vlen, unsigned int, flags, struct __kernel_timespec *, timeout)

#undef IVLSYS0
#undef IVLSYS1
#undef IVLSYS2
#undef IVLSYS3
#undef IVLSYS4
#undef IVLSYS5
#undef IVLSYS6
